instajs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.list, name="root"),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.people, name='people'),
]

# static(통과시키고자 하는 url, 실제 저장 장소)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path('', views.list, name="list"),
    path('create/', views.create, name='create'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'),
    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comment/<int:comment_id>/remove', views.comment_remove, name='comment_remove'),
]  

posts/models.py
from django.db import models
# from django.contrib.auth.models import User를 settings에서 불러와서 사용한다.
from django.conf import settings

class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
    __str__ = __repr__ = lambda self: f"{self.id}) {self.content}"


class Comment(models.Model):
    content = models.CharField(max_length=150)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    __str__ = __repr__ = lambda self: f"{self.id}) {self.user} => {self.post.user}: {self.content[:30]}"

templates/instajs/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="row">
  <form method="POST" class="col-12" enctype="multipart/form-data"> <!-- 이미지를 폼에서 받기위해 enctype 추가 -->
    <!--모델 폼-->
    <!--{{ form }}-->
    {% bootstrap_form form %}  
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">업로드</button>
  </form>
</div>
{% endblock %}

templates/instajs/list.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body%}
  <div class="row justify-content-center">
    {% if posts %}
      {% for post in posts %}
      <div class="card m-3" style="width: 20rem;">
        {% if post.image %}
        <img src="{{ post.image.url }}" class="card-img-top" alt="user image">
        {% else %}
        <img src="https://picsum.photos/400/300/?random" class="card-img-top" alt="user image">
        {% endif %}
        <div class="card-header">
          <a href="{% url 'people' post.user.username %}">
            <span>{{ post.user.username }}</span>
          </a>
        </div>
        <div class="card-body">
          <p class="card-text">{{ post.content }}</p>
          <!-- 작성자만 수정/삭제 가능 -->
          {% if post.user == request.user %}
          <div class="btn-group" role="group" aria-label="Basic example">
            <a href="{% url 'posts:update' post.id %}" class="btn btn-success">수정</a>
            <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger">삭제</a>
          </div>
          {% endif %}
        </div>
        <!-- 좋아요 버튼 추가 -->
        <div class="card-body">
          <a class="side-menu" href="{% url 'posts:like' post.id %}">
            {% if user in post.like_users.all %}
            <i class="fas fa-heart like"></i>
            {% else %}
            <i class="far fa-heart liked"></i>
            {% endif %}
          </a>
          {{ post.like_users.count }}명이 좋아합니다.
        </div>
        <div class="card-body">
          <div class="card-text">
            <!-- Comment ModelForm -->
            <form action="{% url 'posts:comment_create' post.id %}" method="POST">
              <!-- Bootstrap Form -->
              {% bootstrap_form comment_form %}
              {% csrf_token %}
            </form>
            <!-- 해당 글에 작성된 댓글을 모두 출력-->
          </div>
          {% for comment in post.comment_set.all %}
          <div class="card-text">
            <strong>{{ comment.user.username }}</strong>
            <span>{{ comment.content }}</span>
            <a href="{% url 'posts:comment_remove' post.id comment.id %}" class="text-danger">
              <i class="fas fa-times"></i>
            </a>
          </div>
          {% empty %}
          <div class="card-text">
            <span>댓글이 없습니다.</span>
          </div>
          {% endfor %}
        </div>
      </div>
      {% empty %}
      <p>다른 친구들을 팔로우 해보세요!</p>
      {% endfor %}
    {% endif %}
  </div>
{% endblock %}

templates/instajs/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="row">
  <form method="POST" class="col-12" enctype="multipart/form-data">
    <!--모델 폼-->
    <!--{{ form }}-->
    {% bootstrap_form form %}  
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">업로드</button>
  </form>
</div>
{% endblock %}