accounts/urls.py
from django.urls import path
from django.conf import settings

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.password, name='password'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

instajs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.list, name="root"),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.people, name='people'),
]

# static(통과시키고자 하는 url, 실제 저장 장소)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path('', views.list, name="list"),
    path('create/', views.create, name='create'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'),
    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comment/<int:comment_id>/remove', views.comment_remove, name='comment_remove'),
]  

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    nickname = models.CharField(max_length=48, blank=True)
    image = models.ImageField(upload_to='profile', default='profile/default-profile.jpg', blank=True)
    
    __str__ = lambda self: f"{self.id}) {self.user}({self.nickname}) -- {self.description[:30]}"


class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")
    

posts/models.py
from django.db import models
# from django.contrib.auth.models import User를 settings에서 불러와서 사용한다.
from django.conf import settings

class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    
    __str__ = __repr__ = lambda self: f"{self.id}) {self.content}"


class Comment(models.Model):
    content = models.CharField(max_length=150)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    __str__ = __repr__ = lambda self: f"{self.id}) {self.user} => {self.post.user}: {self.content[:30]}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserChangeForm,
    UserCreationForm,
)
from django.contrib.auth import get_user_model

from . import models

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', ]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ['nickname', 'description', 'image']


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        # fields를 그대로 쓰니까 정의하지 않고 그대로 사용해도 좋다.
        # fields = UserCreationForm.Meta.fields
        # fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    get_user_model,
    update_session_auth_hash,
)
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm,
)
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import (
    CustomUserChangeForm,
    CustomUserCreationForm,
    ProfileForm,
)
from .models import Profile


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            # next가 정의되어 있으면 해당하는 url로 리다이렉트
            # 정의되어있지 않으면 posts:list로 리다이렉트
            return redirect(request.GET.get('next') or 'posts:list')
        return redirect('accounts:login')
    else:
        return render(request, 'accounts/login.html', {'form': AuthenticationForm()})


def logout(request):
    auth_logout(request)
    return redirect('posts:list')


def signup(request):
    if request.method == "POST":  # 유저 등록
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            auth_login(request, user)
        return redirect("posts:list")
    else:  # GET: 유저 정보 입력
        return render(request, 'accounts/signup.html', {'form': CustomUserCreationForm()})


def people(request, username):
    # 사용자에 대한 정보
    # 1. django.contrib.auth.get_user_model()
    # 2. django.conf.settings.AUTH_USER
    # 3. django.contrib.auth.models.User (X)
    person = get_object_or_404(get_user_model(), username=username)
    return render(request, 'accounts/people.html', {'people': person})
    

@login_required
def update(request):
    """회원 정보 변경"""
    if request.method == "POST":
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)
        
        profile = get_object_or_404(Profile, user=request.user)
        profile_form = ProfileForm(data=request.POST, files=request.FILES, instance=profile)
        
        if user_change_form.is_valid():
            user = user_change_form.save()
        else:
            user = request.user
        
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
        
        return redirect("people", user.username)
    else:  # GET
        user_change_form = CustomUserChangeForm(instance=request.user)
        
        profile, created = Profile.objects.get_or_create(user=request.user)
        profile_form = ProfileForm(instance=profile)
        
        return render(request, 'accounts/update.html', {
            'user_change_form': user_change_form,
            'profile_form': profile_form,
        })


@login_required
def delete(request):
    """회원 탈퇴"""
    if request.method == "POST":
        request.user.delete()
        return redirect("accounts:signup")
    else:
        return render(request, 'accounts/delete.html')


@login_required
def password(request):
    """비밀번호 변경"""
    if request.method == "POST":
        password_chage_form = PasswordChangeForm(request.user, request.POST)
        if password_chage_form.is_valid():
            password_chage_form.save()
            update_session_auth_hash(request, request.user)
        return redirect("people", request.user)
    else:
        password_chage_form = PasswordChangeForm(request.user)
        return render(request, 'accounts/password.html', {'password_chage_form': password_chage_form})


@login_required
@require_POST
def follow(request, user_id):
    person = get_object_or_404(get_user_model(), pk=user_id)
    
    if person == request.user:
        return redirect('people', person.username)    
    
    # 만약 현재 유저가 해당 유저를 이미 팔로우 하고 있었으면,
    #  -> 팔로우 취소
    # 아니면
    #  -> 팔로우
    if person in request.user.followings.all():
        request.user.followings.remove(person)
    else:
        request.user.followings.add(person)
    
    return redirect('people', person.username)
        
    

templates/accounts/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  <p>정말로 탈퇴하시겠습니까 ㅠㅠㅠㅠ</p>
  <button class="btn btn-danger" type="submit">미안해요</button>
</form>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1 class="text-center">로그인</h1>
<form method="POST" class="my-4">
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary w-100">로그인</button>
  {% csrf_token %}
</form>
{% endblock %}

templates/accounts/password.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1 class="text-center">비밀번호 변경</h1>
<form method="POST" class="my-4">
  {% bootstrap_form password_chage_form %}
  <button type="submit" class="btn btn-primary w-100">변경</button>
  {% csrf_token %}
</form>
{% endblock %}

templates/accounts/people.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<div class="container">
  <div class="card">
    <div class="card-body">
      <div class="profile-wrapper">
        {% if people.profile.image %}
        <img class="profile-image m-2" src="{{ people.profile.image.url }}"></img>
        {% else %}
        <img class="profile-image m-2" src="{% static '/img/profile/default-profile.jpg' %}"></img>
        {% endif %}
        <div class="profile-text-wrapper d-inline-block">
          <h1 class="card-title d-inline">{{ people.username }}</h1>
          <form class="d-inline" action="{% url 'accounts:follow' people.id %}" method="POST">
            <!-- 만약 현재 접속한 유저가 해당 페이지의 유저를 이미 팔로우한 경우 -->
            {% if user != people %}
              {% if user in people.followers.all %}
              <button class="btn btn-outline-primary" type="submit">unfollow</button>
              {% else %}
              <button class="btn btn-primary" type="submit">follow</button>
              {% endif %}
            {% endif %}
            {% csrf_token %}
          </form>
        </div>
      </div>
      <div class="card-text mr-2 font-weight-bold">{{ people.profile.nickname }}</div>
      <hr/>
      <div class="card-text my-3">{{ people.profile.description }}</div>
      {% if user == people %}
      <hr/>
      <a href={% url 'accounts:update' %} class="btn btn-info">회원 정보 수정</a>
      <a href={% url 'accounts:password' %} class="btn btn-info">비밀 번호 수정</a>
      <a href={% url 'accounts:delete' %} class="btn btn-danger">회원 탈퇴</a>
      {% endif %}
      <div class="row my-4">
      {% for post in people.post_set.all %}
        <div class="profile-posts col-12 col-md-4 overflow-hidden">
        {% if post.image %}
          <img src="{{ post.image.url }}" class="img-fluid"></img>
        {% else %}
          <img src="https://picsum.photos/300/300/?random" class="img-fluid"></img>
        {% endif %}
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1 class="text-center">회원 가입</h1>
<form method="POST" class="my-4">
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary w-100">회원 가입</button>
  {% csrf_token %}
</form>
{% endblock %}

templates/accounts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<h1 class="text-center">회원 정보 수정</h1>
<form method="POST" class="my-4" enctype="multipart/form-data">
  {% bootstrap_form user_change_form %}
  {% bootstrap_form profile_form %}
  <button type="submit" class="btn btn-primary w-100">수정하기</button>
  {% csrf_token %}
</form>
{% endblock %}